[workspace]
resolver = "2"
members = [
    "crates/froglight-data",
    "crates/froglight-extractor",
    "crates/froglight-generator",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["EightFactorial"]
homepage = "https://github.com/EightFactorial/FrogLight-Tools"
repository = "https://github.com/EightFactorial/FrogLight-Tools"
readme = "README.md"

[workspace.dependencies]
async_zip = "0.0.16"
anyhow = "1.0.81"
cafebabe = "0.6.1"
clap = "4.5.3"
convert_case = "0.6.0"
derive_more = "0.99.17"
hashbrown = "0.14.3"
proptest = "1.4.0"
reqwest = { version = "0.12.2", default-features = false }
serde = "1.0.197"
serde_json = "1.0.114"
strum = "0.26"
strum_macros = "0.26"
tokio = "1.36.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[workspace.lints.rust]
missing_docs = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
unused_lifetimes = "warn"
unused_import_braces = "warn"
unreachable_pub = "warn"

[workspace.lints.rustdoc]
bare_urls = "deny"
broken_intra_doc_links = "deny"
private_intra_doc_links = "deny"
invalid_codeblock_attributes = "deny"
invalid_rust_codeblocks = "deny"
invalid_html_tags = "deny"

[workspace.lints.clippy]
cast_possible_truncation = "warn"
cast_possible_wrap = "warn"
module_name_repetitions = "allow"
needless_pass_by_value = "allow"
pedantic = "warn"
unnecessary_cast = "warn"
