[workspace]
resolver = "2"
members = [
    "crates/froglight-definitions",
    "crates/froglight-extract",
    "crates/froglight-generate",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["EightFactorial"]
homepage = "https://github.com/EightFactorial/FrogLight-Tools"
repository = "https://github.com/EightFactorial/FrogLight-Tools"
readme = "README.md"

[workspace.dependencies]
anyhow = "1.0.82"
cafebabe = "0.6.1"
convert_case = "0.6.0"
derive_more = "0.99.17"
enum_dispatch = "0.3.13"
hashbrown = "0.14.3"
itertools = "0.12.1"
proptest = "1.4.0"
reqwest = { version = "0.12.3", default-features = false }
serde = "1.0.198"
serde_json = "1.0.116"
tokio = "1.37.0"
tracing = "0.1.40"
vergen = "8.3.1"

[workspace.lints.rust]
missing_docs = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
unused_lifetimes = "warn"
unused_import_braces = "warn"
unreachable_pub = "warn"

[workspace.lints.rustdoc]
bare_urls = "deny"
broken_intra_doc_links = "deny"
private_intra_doc_links = "deny"
invalid_codeblock_attributes = "deny"
invalid_rust_codeblocks = "deny"
invalid_html_tags = "deny"

[workspace.lints.clippy]
cast_possible_truncation = "warn"
cast_possible_wrap = "warn"
module_name_repetitions = "allow"
needless_pass_by_value = "allow"
pedantic = "warn"
unnecessary_cast = "warn"
