[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"

[licenses]
default = "deny"
copyleft = "warn"
unlicensed = "deny"
allow = [
    "MIT",
    #    "MIT-0",
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    #    "Zlib",
    "0BSD",
    #    "BSD-2-Clause",
    #    "CC0-1.0",
    "MPL-2.0",
    "OpenSSL",
]

[[licenses.exceptions]]
name = "unicode-ident"
allow = ["Unicode-DFS-2016"]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
[[licenses.clarify.license-files]]
path = "LICENSE"
hash = 3171872035

[sources]
unknown-git = "deny"
unknown-registry = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

[bans]
highlight = "all"
wildcards = "deny"
multiple-versions = "warn"
external-default-features = "allow"
workspace-default-features = "allow"

[[bans.skip]]
name = "bitflags"
version = "1.3.2"

# Other
[[bans.skip]]
name = "redox_syscall"

# Windows
[[bans.skip]]
name = "windows-sys"
[[bans.skip]]
name = "windows-targets"
[[bans.skip]]
name = "windows_aarch64_gnullvm"
[[bans.skip]]
name = "windows_aarch64_msvc"
[[bans.skip]]
name = "windows_i686_gnu"
[[bans.skip]]
name = "windows_i686_msvc"
[[bans.skip]]
name = "windows_x86_64_gnu"
[[bans.skip]]
name = "windows_x86_64_gnullvm"
[[bans.skip]]
name = "windows_x86_64_msvc"
