[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"

[licenses]
default = "deny"
copyleft = "warn"
unlicensed = "deny"
allow = [
    "MIT",
    #    "MIT-0",
    "Apache-2.0",
    #    "BSD-3-Clause",
    #    "ISC",
    #    "Zlib",
    #    "0BSD",
    #    "BSD-2-Clause",
    #    "CC0-1.0",
]

[[licenses.exceptions]]
name = "unicode-ident"
allow = ["Unicode-DFS-2016"]

[sources]
unknown-git = "deny"
unknown-registry = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

[bans]
highlight = "all"
wildcards = "deny"
multiple-versions = "warn"
external-default-features = "allow"
workspace-default-features = "allow"
