[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
version = 2

[licenses]
allow = [
  "0BSD",
  "Apache-2.0",
  "BSD-3-Clause",
  "CDLA-Permissive-2.0",
  "ISC",
  "MIT",
  "Unicode-3.0",
  "Zlib",
  # "BSD-2-Clause",
  # "CC0-1.0",
  # "MIT-0",
  # "MPL-2.0",
  # "OpenSSL",
]

[sources]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
unknown-git = "deny"
unknown-registry = "deny"

[bans]
external-default-features = "allow"
highlight = "all"
multiple-versions = "warn"
wildcards = "deny"
workspace-default-features = "allow"

[[bans.skip]]
name = "bitflags"
version = "=1.3.2"
[[bans.skip]]
name = "getrandom"
version = "=0.2.16"
[[bans.skip]]
name = "regex-automata"
version = "=0.1.10"
[[bans.skip]]
name = "regex-syntax"
version = "=0.6.29"
[[bans.skip]]
name = "wasi"
version = "=0.11.0"

# [[bans.skip]]
# name = "windows-strings"
[[bans.skip]]
name = "windows-sys"
# [[bans.skip]]
# name = "windows-targets"
# [[bans.skip]]
# name = "windows_aarch64_gnullvm"
# [[bans.skip]]
# name = "windows_aarch64_msvc"
# [[bans.skip]]
# name = "windows_i686_gnu"
# [[bans.skip]]
# name = "windows_i686_gnullvm"
# [[bans.skip]]
# name = "windows_i686_msvc"
# [[bans.skip]]
# name = "windows_x86_64_gnu"
# [[bans.skip]]
# name = "windows_x86_64_gnullvm"
# [[bans.skip]]
# name = "windows_x86_64_msvc"
