[package]
name = "froglight-generate"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
build = "build.rs"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[build-dependencies]
vergen-gix = { workspace = true, features = ["build"] }

[dependencies]
anyhow = { workspace = true }
convert_case = { workspace = true }
enum_dispatch = { workspace = true }
froglight-definitions = { version = "0.1.0", path = "../froglight-definitions" }
froglight-extract = { version = "0.1.0", path = "../froglight-extract" }
hashbrown = { workspace = true, features = ["serde"] }
prettyplease = { version = "0.2.22", features = ["verbatim"] }
proc-macro2 = { version = "1.0.87", features = ["nightly"] }
serde = { workspace = true }
serde_json = { workspace = true, features = ["preserve_order"] }
serde_unit_struct = "0.1.3"
quote = "1.0.37"
syn = { version = "2.0.79", features = ["extra-traits", "full"] }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
