//! TODO

pub mod asset;
pub use asset::GeneratedAssets;

pub mod data;
pub use data::GeneratedData;

pub mod report;
pub use report::GeneratedReports;

#[cfg(test)]
mod test;
mod traits;

/// Data generated for a specific [`Version`].
///
/// Generated by Mojang's built-in data generators.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratorData {
    /// Generated assets.
    pub assets: GeneratedAssets,
    /// Generated data.
    pub data: GeneratedData,
    /// Generated reports.
    pub reports: GeneratedReports,
}
