[package]
name = "froglight-extract"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
build = "build.rs"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[build-dependencies]
vergen-gix = { workspace = true, features = ["build"] }

[dependencies]
anyhow = { workspace = true }
async_zip = { version = "0.0.17", features = ["full", "tokio", "tokio-fs"] }
cafebabe = { workspace = true }
enum_dispatch = { workspace = true }
froglight-definitions = { version = "0.1.0", path = "../froglight-definitions" }
futures-lite = { workspace = true }
hashbrown = { workspace = true, features = ["serde"] }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, features = ["preserve_order"] }
serde_unit_struct = "0.1.3"
tokio = { workspace = true, features = ["io-std", "io-util"] }
tracing = { workspace = true }
walkdir = "2.5.0"
