name: Clippy

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.rs"
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - ".github/workflows/clippy.yml"

env:
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    permissions:
      # Required to upload the results
      security-events: write
    steps:
      # Get the nightly toolchain
      - name: Toolchain
        uses: dtolnay/rust-toolchain@1482605bfc5719782e1267fd0c0cc350fe7646b8 # v1
        with:
          toolchain: nightly
          components: clippy
      # Install clippy-sarif and sarif-fmt
      - name: Install Sarif
        uses: taiki-e/install-action@9023ed54c080c7ff1b3e4af335c729c3f9cb1dd7 # v2
        with:
          tool: clippy-sarif,sarif-fmt
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      # Restore/Setup the cache
      - name: Cache
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2
      # Run the clippy tool
      - name: Run Clippy
        run: >
          cargo clippy --workspace --all-targets -- -D warnings
          | clippy-sarif
          | tee clippy-results.sarif
          | sarif-fmt
        continue-on-error: true
      # Upload the results
      - name: Upload Results
        uses: github/codeql-action/upload-sarif@df409f7d9260372bd5f19e5b04e83cb3c43714ae # v3
        with:
          sarif_file: clippy-results.sarif
          wait-for-processing: true
      # Print the results
      - name: Report Results
        run: cargo clippy --workspace --all-features --all-targets -- -D warnings
        continue-on-error: true
