name: Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "Cargo.lock"
      - "src/**.rs"
      - "crates/**.rs"
  push:
    branches:
      - main
    paths:
      - "Cargo.lock"
      - "src/**.rs"
      - "crates/**.rs"
      - ".github/workflows/testing.yml"

env:
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      # Install required libraries
      - name: Libraries
        if: runner.os == 'linux'
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      # Install a newer version of Java
      - name: Setup Java
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4
        with:
          distribution: "temurin"
          java-version: "21"
          java-package: "jre"
      # Get the nightly toolchain
      - name: Toolchain
        uses: dtolnay/rust-toolchain@1482605bfc5719782e1267fd0c0cc350fe7646b8 # v1
        with:
          toolchain: nightly
      # Install the nextest tool
      - name: Install Nextest
        uses: taiki-e/install-action@959f8ad90499c9ce5d072830b8ca80b6edd1d13f # v2
        with:
          tool: nextest
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      # Restore/Setup the cache
      - name: Cache
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2
      # Run the nextest tool
      - name: Run Nextest
        run: cargo nextest run --workspace --all-targets --test-threads 1
      # Run doctests separately
      - name: Run Doctests
        run: cargo test --doc --workspace
      # Cleanup the cache
      - name: Cleanup
        run: rm -rf target/froglight-parse
