use hashbrown::HashMap;
use serde::{Deserialize, Serialize};
use serde_json::Value;

/// A block report generated by the `Server` jar.
///
/// Contains all blockstates, their ids, and their properties.
///
/// Typically located at `generated/reports/blocks.json`.
#[derive(Debug, Default, Clone, Serialize, Deserialize)]
pub struct BlocksReport(pub HashMap<String, BlockData>);

impl std::ops::Deref for BlocksReport {
    type Target = HashMap<String, BlockData>;
    fn deref(&self) -> &Self::Target { &self.0 }
}
impl std::ops::DerefMut for BlocksReport {
    fn deref_mut(&mut self) -> &mut Self::Target { &mut self.0 }
}

/// Block states and properties of a specific block.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BlockData {
    /// The block definition.
    pub definition: BlockDefinition,

    /// A list of all blockstates.
    pub states: Vec<BlockState>,

    /// A map of all blockstate properties and their possible values.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub properties: HashMap<String, Vec<String>>,
}

/// A block definition with its type and properties.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BlockDefinition {
    /// The block type.
    #[serde(rename = "type")]
    pub r#type: String,
    /// The block properties.
    #[serde(default)]
    pub properties: HashMap<String, Value>,
    /// Other properties.
    #[serde(flatten)]
    pub other: HashMap<String, Value>,
}

/// A blockstate with its id and properties.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BlockState {
    /// If the blockstate is the default one.
    #[serde(default, skip_serializing_if = "BlockState::not_default")]
    pub default: bool,

    /// The blockstate id.
    ///
    /// This is the id stored in chunks and send over the network.
    #[serde(alias = "id")]
    pub protocol_id: u32,

    /// The blockstate properties.
    ///
    /// All properties inside the parent [`BlockData`] must be present.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub properties: HashMap<String, String>,
}

impl BlockState {
    /// Skip serializing the [`BlockState::default`] field if it is [`false`].
    #[must_use]
    pub const fn not_default(default: &bool) -> bool { !*default }
}
